name: first-excercise-workflow
on: [push, pull_request]

jobs:
  check-python_pip:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Check Python Version
        run: python --version
      - name: 2. Check PIP Version
        run: pip --version